### ISSUE TITLE
Select versioning scheme

### ISSUE THREAD

**Issue by ryansb** [ryansb/crop#1]
Right now CROP can create new artifacts on existing products, but the versioning scheme leaves something to be desired. The artifacts are referring to the CFN templates by S3 object version (if versioning is on), but the artifacts are currently always named `2`. There are a couple ways forward:

1. List all existing artifacts, find the one with the highest `int` name, add 1, and use that as the name. This is a straightforward scheme as long as int-versions are ok
2. Try to detect a git repo hash and use the short hash as the name, so the artifact is associated to a VCS checkout
3. Allow a `--version [any string]` option so users can pick their own strategy.

**Comment by shortjared** [comment]
#3 is pretty much required. Very often I can imagine people would want CROP release version tied directly to product version names.

**Comment by shortjared** [comment]
In the same area of work, "description" should also be a configurable option on deploy.

**Comment by ryansb** [comment]
Done in https://github.com/ryansb/crop/commit/639471a58db07183dab5f5969432e57220dbd246

**Comment by ryansb** [comment]
The default version is `2`.
